### ISSUE TITLE
pyusb module does not discover device in Windows 10

### ISSUE THREAD

**Issue by RufusVS** [cdtx/mcp2200#10]
I have been looking for a way to control a denkovi relay module board V2 which uses the MCP2200 chipset.
All the examples I've found have used pyusb to enumerate the device, but it does not see it on my Windows System.
does this code work on linux and mac and not windows?   I am trying to find a way to connect to the HID device and I don't think
the method used will work for me.  I'll download the project and see what happens, but I'll probably get similar results to the last
3 examples from other places I tried.
(Edit:  Finally got it to work with python and the hidapi module.  It took a long time to put scattered pieces together and using some MCP2221 example python code to get the idea.  A minimal python program to turn on and off a relay follows.
You may need to uninstall and remove device drivers for the relay unit and reinstall to get the standard drivers.)

```import hid
import sys

MCP2200_SET_CLEAR_OUTPUTS=0x08
RELAY_NUM = 1
RELAY_MASK = 0x0F

if len(sys.argv) > 1:
    RELAY_NUM = int(sys.argv[1])

SET_MASK = 1 << (RELAY_NUM - 1)
CLR_MASK = RELAY_MASK ^ SET_MASK

h = hid.device()
h.open(0x04d8, 0x00df)                  # Microchip MCP2200
buf = ([0] +                            # report 0
    [MCP2200_SET_CLEAR_OUTPUTS] +       # relay set/clear
    [0]*10 +                            # unused
    [SET_MASK] + 
    [CLR_MASK] +    
    [0]*3)
t = h.write(buf)
h.close()

```

**Comment by FKW9** [comment]
Hello, did you make any progress?
I am also having troubles under Windows 10.
With the default drivers and the given examples I can’t find nor connect to the device.

I then tried a different driver for Interface 0 (CDC), called **libusb-win32 (v1.2.6.0)**. With this driver I can at least find the device, but using the same examples again, I get the following output:

```
>>> import sys
>>> from cdtx.mcp2200.device import MCP2200Device
>>> dev = MCP2200Device(autoConnect=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Desktop\ENV\lib\site-packages\cdtx\mcp2200\device.py", line 17, in __init__
    self.connect()
  File "C:\Users\User\Desktop\ENV\lib\site-packages\cdtx\mcp2200\device.py", line 37, in connect
    self.epIn = self.dev[0][(MCP2200_HID_INTERFACE,0)][0]
 File "C:\Users\User\Desktop\ENV\lib\site-packages\usb\core.py", line 641, in __getitem__
    return Interface(self.device, index[0], index[1], self.index)
  File "C:\Users\User\Desktop\ENV\lib\site-packages\usb\core.py", line 456, in __init__
    desc = backend.get_interface_descriptor(
  File "C:\Users\User\Desktop\ENV\lib\site-packages\usb\backend\libusb0.py", line 466, in get_interface_descriptor
    raise IndexError('Invalid interface index ' + str(intf))
IndexError: Invalid interface index 2
```

Looking deeper into the library, I changed the interface index to 0:
https://github.com/cdtx/mcp2200/blob/1d936813baee2e2c00b6ac90ff84d4815e527406/cdtx/mcp2200/device.py#L9
This does not make sense though, because the HID Interface is 2? I do not quite understand.
With this change I get a new exception:

```
>>> from cdtx.mcp2200.api import SimpleIOClass
>>> dev = SimpleIOClass()
>>> dev.InitMCP2200(0x04d8, 0x00df)
>>> assert dev.GetNoOfDevices() == 1
>>> dev.SelectDevice(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Desktop\ENV\lib\site-packages\cdtx\mcp2200\api.py", line 197, in SelectDevice
    self.device.connect(self.vid, self.pid, uiDeviceNo)
  File "C:\Users\User\Desktop\ENV\lib\site-packages\cdtx\mcp2200\device.py", line 38, in connect
    self.epOut = self.dev[0][(MCP2200_HID_INTERFACE,0)][1]
  File "C:\Users\User\Desktop\ENV\lib\site-packages\usb\core.py", line 513, in __getitem__
    return Endpoint(
  File "C:\Users\User\Desktop\ENV\lib\site-packages\usb\core.py", line 326, in __init__
    desc = backend.get_endpoint_descriptor(
  File "C:\Users\User\Desktop\ENV\lib\site-packages\usb\backend\libusb0.py", line 478, in get_endpoint_descriptor
    raise IndexError('Invalid endpoint index ' + str(ep))
IndexError: Invalid endpoint index 1
 ```

From this point I do not quite know what to do further, since that USB stuff is not really my area of expertise.
Furthermore, searching online for a solution was also not really successful.

OS: Windows 10
Python: 3.8.8

**Comment by Vodsgaard** [comment]
any progress?

**Comment by RufusVS** [comment]
> any progress?

Not on my end.  Haven't had a chance to look at it in a while, though.  The relay is sitting in my pile of things to get back to...

**Comment by FKW9** [comment]
Nope. I just built a wrapper around the DenkoviCommandLineTool.jar which just executes it with some parameters in a shell.
It is very slow, but works.

For the other relay boards I've ordered I chose the ones with FT245 chip, which is much easier to control in windows/linux.

**Comment by RufusVS** [comment]
This is just a heads-up.  Microchip has demo boards for the MCP2200 and some support software.   I don't think the usb-to-chip circuitry is any different with the relay board.  I'll be back with more results soon...

**Comment by RufusVS** [comment]
After lots of time and lots of reading and looking at code in different languages and for different microchip chips...
Here is a simple python program to turn on a relay.  I have some other short programs but this boils it down to the simplest forms without extra output or error detection.  I had to play around with the installed drivers, so ultimately I uninstalled all the devices at `VID:0x04D8  PID:0x00DF`  and checked the "remove driver" box.  Then replugged the device and let windows choose the drivers to make the program work.
I saved this program as turnon.py  so you can call:
`turnon.py 1`
to turn on the first relay.  If python doesn't automatically run, try:
`python turnon.py 1`
(I'm not sure if the sys.argv has to be modified for that second call as I haven't tried it.)

```import hid
import sys

MCP2200_SET_CLEAR_OUTPUTS=0x08
RELAY_NUM = 1
RELAY_MASK = 0x0F

if len(sys.argv) > 1:
    RELAY_NUM = int(sys.argv[1])

SET_MASK = 1 << (RELAY_NUM - 1)
CLR_MASK = RELAY_MASK ^ SET_MASK

h = hid.device()
h.open(0x04d8, 0x00df)                  # Microchip MCP2200
buf = ([0] +                            # report 0
    [MCP2200_SET_CLEAR_OUTPUTS] +       # relay set/clear
    [0]*10 +                            # unused
    [SET_MASK] + 
    [CLR_MASK] +    
    [0]*3)
t = h.write(buf)
h.close()

```
