### ISSUE TITLE
Missing parameter EEP_Addr

### ISSUE THREAD

**Issue by mario-chirinos** [cdtx/mcp2200#6]
File "/home/mchc/git/mcp2200/cdtx/mcp2200/device.py", line 60, in func_wrapper
    raise Exception('Missing parameter %s' % p)
Exception: Missing parameter EEP_Addr
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    dev.write_ee(0, 12)
  File "/home/mchc/git/mcp2200/cdtx/mcp2200/device.py", line 60, in func_wrapper
    raise Exception('Missing parameter %s' % p)
Exception: Missing parameter EEP_Addr

**Comment by cdtx** [comment]
Hi,
As you can see this project has been archived before really mature, because of a lack of time.
I'd be glad to integrate any fix you would send me.
